apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "nextcloud.fullname" . }}
  labels:
    type: nfs
    name: {{ template "nextcloud.name" . }}
spec:
  capacity:
    storage: {{ .Values.persistentVolume.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/IT-Academy/nfs-data/sa2-25-23/Ivanchuk_Pavel 
    server: 192.168.37.105
