ind: Service
apiVersion: v1
metadata:
  name: {{ template "my-nextcloud.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "my-nextcloud.name" . }}
    chart: {{ template "my-nextcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "my-nextcloud.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "my-nextcloud.fullname" . }}-preview
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ template "my-nextcloud.name" . }}
    chart: {{ template "my-nextcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "my-nextcloud.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80
