name: Building pishing and charting Nextcloud
on:
  push:
    branches:
      - master

jobs:
  bump-ver-push-tag:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_version.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.TOKEN_GIT }}

  docker-lint:
    name: Docker Lint
    needs: bump-ver-push-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Docker Lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Docker-nextcloud/Dockerfile
          failure-threshold: error, warning

  build-and-push-image:
    name: Build and push image
    needs: [bump-ver-push-tag, docker-lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Login to GitHub Packages Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GIT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/Docker-nextcloud:${{ needs.bump-ver-push-tag.outputs.tag }} ./Docker-nextcloud
          docker push ghcr.io/${{ github.repository }}/Docker-nextcloud:${{ needs.bump-ver-push-tag.outputs.tag }}

  generate-chart:
    name: Generate Chart
    needs: bump-ver-push-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Update appVersion & Chart version
        run: |
          sed -i "s/^version:.*$/version: ${{ needs.bump-ver-push-tag.outputs.tag }}/" ./my-nextcloud/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: ${{ needs.bump-ver-push-tag.outputs.tag }}/" ./my-nextcloud/Chart.yaml

      - name: Commit changes
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_MAIL"
          git add .
          git commit -m "Update Chart to ${{ needs.bump-ver-push-tag.outputs.tag }} by GitHub Actions"
          git push origin main

  lint-helm:
    name: Helm Lint
    needs: generate-chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: v3.5.0

      - name: Helm lint
        run: |
          helm lint ./my-nextcloud

  chart-release:
    name: Chart release
    needs: [bump-ver-push-tag, lint-helm, build-and-push-image]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: 'master'

      - name: Install Helm
        uses: Azure/setup-helm@v3
        with:
          version: v3.5.0

      - name: Sync Repo
        run: cd ./nextcloud-v && sh helm-package.sh

      - name: Move folder
        run: |
          mv ./nextcloud-v/* ./
          cd ./
          helm repo index --url https://ipaul32.github.io/my-nextcloud/ --merge index.yaml .
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_MAIL"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Chart version ${{ needs.bump-ver-push-tag.outputs.tag }}" -m "${{ github.event.head_commit.message }}"
          git push
  
      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github_action
          SLACK_COLOR: '#006400'
          SLACK_ICON: 'https://github.com/rtCamp.png?size=48'
          SLACK_MESSAGE: 'Nextcloud built'
          SLACK_TITLE: 'SUCCESS!'
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github_action
          SLACK_COLOR: '#8B0000'
          SLACK_ICON: 'https://github.com/rtCamp.png?size=48'
          SLACK_MESSAGE: 'You have errors or mistakes in your jobs'
          SLACK_TITLE: 'FAILURE!'
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
